### PR TITLE
Reapplying fix from #1

### PR DESCRIPTION
**Pull request by waschinski**
Reapplying password fix from #1. It looks like the whole merge from the PR got removed since your last merge also contains the changes for multiple ways to obtain the container id. No idea where it got lost though.

### CODE REVIEW

**Comment by waschinski** [comment]
I was just updating the docker image and the mariadb backup failed due to this change missing.

**Comment by waschinski** [comment]
@foorschtbar Please have a look at this. ;)

**Comment by foorschtbar** [comment]
Sry 🤦🏻‍♂️

**Comment by waschinski** [comment]
Thanks for merging @foorschtbar. The repo doesn't seem to miss anything else which was even more curious but then who never messed up something in Git? I surely did. 😄

**Pull request merged**
